---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache (on Debian)
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_distribution == "Ubuntu"

- import_playbook: ../../site.yml
