---

- name: install apache
  hosts: all
  become: true
  tasks:
    - name: install apache
      yum:
        name:
          - httpd
          - httpd-devel
        state: present
    - name: copy configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd.vhosts
          dest: /etc/httpd/conf/httpd-vhosts.conf

    - name: Ensure apache is started and configure it to run at boot
      service:
        name: http
        state: started
        enabled: true
